#!/usr/bin/env python3
"""Derive canonical Montgomery Frobenius constants with integer arithmetic.

From the repository root:
python3 syscall/solana-bn254/scripts/generate_extension_constants.py \\
    | rustfmt --edition 2024 \\
    > syscall/solana-bn254/src/backend/frobenius.rs
"""

Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583
R = 1 << 256
XI = (9, 1)


def multiply(a, b):
    return ((a[0] * b[0] - a[1] * b[1]) % Q,
            (a[0] * b[1] + a[1] * b[0]) % Q)


def power(a, exponent):
    result = (1, 0)
    while exponent:
        if exponent & 1:
            result = multiply(result, a)
        a = multiply(a, a)
        exponent >>= 1
    return result


def coefficient(value):
    value = value * R % Q
    if value == 0:
        return 'U256::zero()'
    limbs = [(value >> (64 * i)) & ((1 << 64) - 1) for i in range(4)]
    return 'U256::new([' + ', '.join(f'0x{x:016x}' for x in limbs) + '])'


def generate():
    lines = [
        '//! Frobenius multipliers for the BN254 extension tower.',
        '//!',
        '//! Generated by `scripts/generate_extension_constants.py` using',
        '//! integer arithmetic in `Fq2 = Fq[u]/(u^2+1)`, with `xi = 9+u`.',
        '//! Every limb array represents a reduced coefficient times `2^256 mod q`.',
        '',
        'use super::{Fq2, U256};',
        '',
    ]
    for name, length, numerator, denominator in [
        ('FQ6_C1', 6, 1, 3), ('FQ6_C2', 6, 2, 3), ('FQ12_C1', 12, 1, 6)
    ]:
        lines.append(f'// xi^({numerator}*(q^k-1)/{denominator}), for k = 0..{length}.')
        lines.append(f'pub(super) const {name}: [Fq2; {length}] = [')
        for k in range(length):
            exponent, remainder = divmod(numerator * (Q ** k - 1), denominator)
            assert remainder == 0
            a, b = power(XI, exponent)
            if (a, b) == (1, 0):
                lines.append('    Fq2::ONE,')
            else:
                lines.append(f'    Fq2 {{ c0: {coefficient(a)}, c1: {coefficient(b)} }},')
        lines.extend(['];', ''])
    return '\n'.join(lines)


if __name__ == '__main__':
    print(generate())
